[WEA-19] :lipstick: 글로벌 스크롤 탑이동 버튼
team0102/weather-frontend pull request #14
Opened 2024-01-20 18:03 UTC by leechengwon

2024-01-21 04:11 UTC, JISUlicious commented on src/components/GlobalTopBtn/GlobalTopBtn.jsx
> +const GlobalTopBtn = () => {
일부 버튼은 이름에 Button을 사용하고, 일부는 Btn을 사용하게 되면 사용하다가 혼동이 있지 않을까 싶습니다. 
한쪽으로 통일해보는 것은 어떨까요?

2024-01-21 04:18 UTC, JISUlicious requested changes

2024-01-21 04:18 UTC, JISUlicious commented on src/components/GlobalTopBtn/GlobalTopBtn.jsx
> +const GlobalTopBtn = () => {
일부 버튼은 Button을 사용하고, 일부는 Btn을 사용하면 사용 할 때 혼동이 있지 않을까 싶습니다. 한 쪽으로 통일시키는 것은 어떨까요?

2024-01-23 01:54 UTC, leechengwon commented on src/components/GlobalTopBtn/GlobalTopBtn.jsx
> +const GlobalTopBtn = () => {
반영하겠습니다.

2024-01-23 04:25 UTC, JISUlicious approved these changes

2024-01-23 04:25 UTC, merged